spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_learning_platform_db?createDataBaseIfNotExist=true
    password: 1234
    username: root

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  security:
    user:
      password: Yasu2237451
