spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_learning_platform_db?CreateDataBaseIfNotExist=true
    password: 1234
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
